### ISSUE TITLE
4.0 release checklist

### ISSUE THREAD

**Issue by naugtur** [AmpersandJS/ampersand-sync#67]
- [x] write docs in README.md (It's weird that this project doesn't have usage in readme)
- [x] npm version major
- [x] publish 
- [x] inform ampersand-model and ampersand-rest-collection 
- [ ] official docs website update (how are docs updated on main page? where do docs from previous major versions go?)

**Comment by naugtur** [comment]
https://github.com/AmpersandJS/ampersand-model/issues/56
https://github.com/AmpersandJS/ampersand-collection-rest-mixin/issues/27

**Comment by lukekarrys** [comment]
Referencing https://github.com/AmpersandJS/ampersandjs.com/issues/162 for updating the official ampersandjs.com docs.

**Comment by lukekarrys** [comment]
Also created https://github.com/AmpersandJS/ampersand-rest-collection/issues/27 so we remember to update rest-collection as well

**Comment by HenrikJoreteg** [comment]
@naugtur docs get pulled from readme's of individual repos, but a few sections get removed such as credits, etc. That's all handled by the build process for the docs site. Generally changelog section of readme is only place to see previous version info. The only thing you have to do documentation-wise is update local readme and publish to npm.

**Comment by lukekarrys** [comment]
I think this can be closed. The docs will end up on the site once we publish the rest of the modules downstream from this.
